/*
 * Verification API
 *
 * # Introduction  <span class=\"subtext\"> Welcome to the Passbase Verifications API docs. This documentation will help you understand our models and the Verification API with its endpoints. Based on this you can build your own system (i.e. verification) and hook it up to Passbase.  In case of feedback or questions you can reach us under this email address: [developer@passbase.com](mailto:developer@passbase.com). </span>  A User submits a video selfie and valid identifying __Resources__ during a __Verification__ guided by the Passbase client-side integration. Once all the necessary __Resources__ are submitted, __Data points__ are extracted, digitized, and authenticated. These Data points then becomes part of the User's __Identity__. The User then consents to share __Resources__ and/or __Data points__ from their Identity with you. This information is passed to you and can be used to make decisions about a User (e.g. activate account). This table below explains our terminology further.  | Term                                    | Description | |-----------------------------------------|-------------| | Data points                             | Any data about a User extracted from a Resource (E.g. Passport Number, or Age). | | [Resource](#tag/resource_model)         | A source document used to generate the Data points for a User (E.g. Passport). | | [Identity](#tag/identity_model)         | A set of Data points and Resources related to and owned by one single User. This data can be accessed by you through a Verification. | | [User](#tag/user_model)                 | The owner of an email address associated with an Identity. | | Verification (signup)                   | A transaction through which a User consents to share Data points with you. If the Data points you request are not already available in the User's Identity, the Passbase client will ask the User to submit the necessary Resource required to extract them. | | Re-authentication (login)               | A transaction through which a User can certify the ownership of Personal data previously shared through an Authentication. |   # Authentication  <span class=\"subtext\"> There are two forms of authentication for the API: <br/>&bull; API Key <br/>&bull; Bearer JWT Token  </span> 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package passbase

// Monitor politically exposed persons (PEPs), and track risky behavior with adverse media and watchlist checks for a comprehensive customer due diligence and Anti Money Laundering (AML) and Know Your Customer (KYC) program. 
type WatchlistResponse struct {
	// Indicates whether the authentication watchlist check is clean or not
	Clean bool `json:"clean,omitempty"`
	// Watchlist check findings
	Listings *interface{} `json:"listings,omitempty"`
	// List of media entries, with the date, title, and url parameters
	Media []interface{} `json:"media,omitempty"`
	// Array of listing sources (eg. sanction lists)
	Sources []string `json:"sources,omitempty"`
	// What kind of alert or warning is associated with the entity (eg. sanction, pep, warning)
	Types []string `json:"types,omitempty"`
}
